### PR TITLE
Login, logout, header/footer, nav complete.

### PR DESCRIPTION
**Pull request by kimberlym4488**
- [x] /login and /signup functionality complete with handlebars and js
- [x] logout functionality complete
- [x] Nav complete with auto login/logout change
- [x] Nav modal added
- [x] Footer github link added
- [x] homepage handlebars complete
- [x] Entering a space id on homepage
- [x] - [ ] Creating a space name on homepage

### CODE REVIEW

**Comment by MikiWolfe** [comment]
Looks great!

**Comment by kimberlym4488** [comment]
Didn't make a base route for /space . Adding and retrying.

**Comment by jmichaelbrown8** [comment]
Looks good so far for the happy path! Before we merge, we might want to give the user some feedback that they need to log in (or possibly just redirect them to login if we get a 403 response back from the create space fetch).

**Comment by ac524** [comment]
@jmichaelbrown8 let's do that as a future task. I'm going merge this as its a huge important change we should get into `main` ASAP to make sure other people are starting from this code base.

Remember, we want to work small and iterate! Make branches for finite purposes, and don't keep adding on scope. If the pull achieves the original purpose, take it and instead go create new issues for additional thoughts you want accomplished.

**Pull request merged**
