### PR TITLE
Added markdown to pitch ideas

### LINKED ISSUE #49: Render the user's content with markdown for formatting
This should be a nice easy way for us to allow the user's to add a little formatting to their project description text :) Would also be a great feature for the `Resource` concept I have in mind.

#### Marked
**Github:** https://github.com/markedjs/marked
**Docs:** https://marked.js.org/
**npm:** https://www.npmjs.com/package/marked

#### highlight
https://www.npmjs.com/package/highlight.js?activeTab=readme#nodejs-on-the-server

**Helpful guide using marked with other technologies to assist with things like syntax highlighting code blocks:** https://javascript.plainenglish.io/revolutionise-the-way-you-write-docs-with-marked-js-5d1de8b8e725?gi=1849262dfcce

### Notes
Thinking we should install this to the server side of the project and use it through a handlebar helper. See the Node guide on the docs page (https://marked.js.org/) for basic usage in node, and tag @ac524 with an questions about how to implement it with a handlebars helper.

Example Node usage from their docs site (using the ES5 `require` for import):
```
const { marked } = require('marked');

const html = marked.parse('# Marked in Node.js\n\nRendered by **marked**.');
```

### PR DESCRIPTION
**Pull request by jmichaelbrown8**
Added marked library into a helper to display markdown for the pitch ideas.

See image for example of it at play!

Screen Shot 2022-03-10 at 10 46 34 PM
!

Resolves #49

### CODE REVIEW

**Review by kimberlym4488 — APPROVED** [review]

**Comment by ac524** [comment]
@jmichaelbrown8 Can you update some of the seed data with simple markdown for samples?

**Comment by ac524** [comment]
@jmichaelbrown8 I'd also love to test out implementing the `highlight` script mention in my issue for rendering code blocks. Let me know if you have any questions.

**Review by ac524 — CHANGES_REQUESTED** [review]
@jmichaelbrown8 one more thing on this. I did a test, and `marked` out of the box does not sanitize HTML, meaning, we are allowing the user to do things like print their own functioning `<script>` tags that they could use to highjack the site.

**See notes on npm page for marked about using an additional library for sanitizing HTML (Under the Usage section)**
https://www.npmjs.com/package/marked

**Review by ac524 — APPROVED** [review]
Perfect. Thanks @jmichaelbrown8. I'm going to merge this in and the highlight script can be a future PR.

**Comment by ac524** [comment]
nevermind! the highlight was in there 🙌  lol. I just somehow got the code without it. Killer : D

**Pull request merged**
