### PR TITLE
Initial Model setup

### PR DESCRIPTION
**Pull request by jmichaelbrown8**
This gets the basic models started with some dummy data. See the schema.drawio file for the intent (edited to add space name and user_id)

Screen Shot 2022-03-01 at 7 37 28 PM

### CODE REVIEW

**Review by kimberlym4488 — APPROVED** [review]
- Should the user who creates the idea be able to enter some sort of date of completion or ETA for their pitch along with a min/max of users for their team.

Nice inclusion of the space model with UUID!!

**Comment by jmichaelbrown8** [comment]
> 

@kimberlym4488, I like those ideas as additional features down the road. For now I think we can get away with the pitcher adding those details into the idea text.

Later on, it would be great to have a target date and skills needed. Then the users could also have a skills offered in the interest table, or in their user profile.

**Comment by ac524** [comment]
@jmichaelbrown8 I think the Space will also need to connect to a user so we can know who created/owns a space

**Comment by jmichaelbrown8** [comment]
Thanks for the comments @ac524! Merged your eslint changes in, fixed all of those errors, and included user_id in Space.

**Pull request merged**
