### PR TITLE
Clicking on 'Space for Ideas' takes you back to your main space

### LINKED ISSUE #79: UX: User clicking on 'space for ideas' subheader takes user back to the space to view all ideas.

### PR DESCRIPTION
**Pull request by kimberlym4488**
Configured with internal script on main view. 
When on '/' route (not in a space) link does not take you anywhere. 

Resolves #79

### CODE REVIEW

**Comment by ac524** [comment]
Hey @kimberlym4488 i would prefer we figure out a way to conditionally render the link in the view file so client side JS isn’t required.

**Comment by kimberlym4488** [comment]
Would I conditionally render this from the route through to handlebars on every single route except '/'?
```


      res.render('idea', {
        idea,
        resources,
        comments,
        space_id,
      });

```

then in view 

```
{{#if space_id}}
href blah blah blah
{{/if}}
```

**Comment by kimberlym4488** [comment]
Should be good to go now @ac524 , thank you for the quick solution!
resolves #79

**Review by ac524 — APPROVED** [review]
Looks good!

**Pull request merged**
