### PR TITLE
Idea endpoint

### PR DESCRIPTION
**Pull request by Jonathan6**
Added homeroute and handlebars for a detailed view on an Idea called by its ID. Includes a VERY basic comment section (with no way to actually comment yet haha)

### CODE REVIEW

**Review by jmichaelbrown8 — CHANGES_REQUESTED** [review]
Looks good to me! Just need to add the idea id on to the link in the ideaMini.handlebars to get those linked up together.

**Review by kimberlym4488 — APPROVED** [review]
Resolved merge conflicts with main and tested functionality. 

- [x ] Create space
- [x ] See existing space and ideas
- [x ] Functioning idea endpoint

**Comment by Jonathan6** [comment]
I coded mini idea to work along side Space.handlebars. I pass in an array into Space.handlebars and the "each" built in helper in handlebars builds it automatically.

**Comment by ac524** [comment]
Opened a new pull after from cherry picking needed commit from here. See #22

**Pull request closed without merging**
